# Downloading Required OMNI and Hpo Data

In [2]:
%load_ext autoreload
%autoreload 2

In [4]:
import pandas as pd

# Get functions for processing hp30
from storm_utils.data_processing import process_hp30_data, process_omni_data
from storm_utils.data_loader import load_hp30_data, load_omni_data

HUXt and HUXt_tools paths configured.

/Users/matthewbillcliff/anaconda3/envs/huxt_3/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Hp30

1. Download data manually from: https://kp.gfz.de/en/hp30-hp60/data

Start date: 01/01/1995    End date: 01/01/2025
Index selection: Hp30     Format Selection: Text File

2. From this page, save as a .txt file using 'ctrl + s' on windows or 'cmd + s' on mac and save to 'storm_utils/shared_data' path

3. Run the following cell to reformat into required dataset

In [5]:
# Process the downloaded hp30 data saved as 'hpodata.txt'
process_hp30_data()

# Check data is processed correctly
loaded_hp30_df = load_hp30_data()
loaded_hp30_df.head()

Saved processed Hp30 data to: /Users/matthewbillcliff/phd_storm_projects/storm_utils/shared_data/hp30.parquet

                      hp30
1995-01-01 00:00:00  1.333
1995-01-01 00:30:00  0.333
1995-01-01 01:00:00  0.333
1995-01-01 01:30:00  0.667
1995-01-01 02:00:00  1.333

## OMNI

1. Download data manually from: https://omniweb.gsfc.nasa.gov/form/dx1.html

2. Select "Create File" at the top of the web page

3. Select resolution: "Hourly Averaged"

4. Start date: 19950101   End date: 20250101

5. Select only "Flow speed, km/sec" in the variable selection

6. Open the ASCII Data File

7. From this page, save as 'omni.txt' using 'ctrl + s' on windows or 'cmd + s' on mac and choose the 'src/data' path

8. Run the following cell to reformat into required dataset

In [8]:
# process the OMNI solar wind data saved as 'omni.txt'
process_omni_data()

# Check data was saved correctly
loaded_omni_df = load_omni_data()
loaded_omni_df.head()

Saved processed OMNI data to: /Users/matthewbillcliff/phd_storm_projects/storm_utils/shared_data/omni_solar_wind.parquet

                     omni_flow_speed
1995-01-01 00:00:00            315.0
1995-01-01 01:00:00            315.0
1995-01-01 02:00:00            320.0
1995-01-01 03:00:00            317.0
1995-01-01 04:00:00            313.0